name: iOS tests

on:
  workflow_dispatch: # Manual trigger for now
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

env:
  DESTINATION: "platform=iOS Simulator,name=iPhone 16,OS=18.4"

jobs:
  build:
    runs-on: macos-15

    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - uses: actions/checkout@v4

      - name: Set environment variable
        run: |
          export DESTINATION="$DESTINATION"

      - name: Build for testing
        run: |
          xcodebuild build-for-testing -scheme "action-tester" -destination "$DESTINATION"

      - name: Test without building
        run: |
          xcodebuild test-without-building -scheme "action-tester" -destination "$DESTINATION"
