name: iOS tests

on:
  workflow_dispatch: # Manual trigger for now
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

env:
  DESTINATION: "platform=iOS Simulator,name=iPhone 16,OS=18.4"

jobs:
  build:
    runs-on: macos-15

    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - uses: actions/checkout@v4

      - name: Set environment variable
        run: |
          export DESTINATION="$DESTINATION"

      - name: Run tests
        run: |
          xcodebuild test -scheme "action-tester" -destination "$DESTINATION" -resultBundlePath Action-Tester.xcresult 

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: Action-Tester-${{ github.run_number }}.xcresult
          path: Action-Tester.xcresult